const express = require('express');
const router = express.Router();
const path = require('path');
const fs = require('fs');
const nodemailer = require('nodemailer');
const dns = require('dns');

// Force IPv4 to avoid ENETUNREACH on IPv6-only hosts
dns.setDefaultResultOrder('ipv4first');

const UPLOADS_DIR = path.join(__dirname, '../../uploads');

// POST /api/email  { to, filename }
router.post('/', async (req, res) => {
  const { to, filename } = req.body;

  if (!to || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(to)) {
    return res.status(400).json({ error: 'Please provide a valid email address.' });
  }

  if (!filename || filename.includes('..') || filename.includes('/') || !filename.endsWith('.docx')) {
    return res.status(400).json({ error: 'Invalid filename.' });
  }

  const filePath = path.join(UPLOADS_DIR, filename);
  if (!fs.existsSync(filePath)) {
    return res.status(404).json({ error: 'File not found. Please regenerate the syllabus.' });
  }

  const smtpUser = process.env.SMTP_USER;
  const smtpPass = process.env.SMTP_PASS;

  if (!smtpUser || !smtpPass) {
    return res.status(500).json({ error: 'Email service is not configured on the server.' });
  }

  try {
    const transporter = nodemailer.createTransport({
      host: 'smtp.gmail.com',
      port: 465,
      secure: true,
      auth: { user: smtpUser, pass: smtpPass },
    });

    await transporter.sendMail({
      from: `"Syllabus Enhancement Tool" <${smtpUser}>`,
      to,
      subject: 'Your Enhanced Syllabus — PES University',
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px;">
          <h2 style="color: #1b3a6b;">Your Enhanced Syllabus is Ready</h2>
          <p>Please find the AI-enhanced syllabus attached as a Word document.</p>
          <p style="color: #666; font-size: 13px; margin-top: 24px;">
            Generated by the PES University Syllabus Enhancement Tool
          </p>
          <p style="color: #b91c1c; font-size: 13px; margin-top: 16px; font-weight: 600;">
            Do not reply to this email. Reach out to the Chairperson or Syllabus Incharge of the department for further clarification.
          </p>
        </div>
      `,
      attachments: [
        {
          filename: 'updated_syllabus.docx',
          path: filePath,
        },
      ],
    });

    res.json({ message: `Syllabus sent to ${to}` });
  } catch (err) {
    console.error('[email] Send error:', err.message, err.code, err.response);
    res.status(500).json({ error: `Failed to send email: ${err.message}` });
  }
});

module.exports = router;
